"""make_sample.py: build a tiny synthetic IQ capture so the viewer runs with
zero downloads.

The real datasets (NIST NASCTN CBRS SEA, NIST I/Q libraries) are multi-GB and
not in this repo. This script fabricates one small SigMF capture with obvious,
recognisable spectrogram structure: a steady carrier, a frequency-hopping tone,
and periodic wideband bursts. Then it runs the normal ingest pipeline
(sigmf_io + iq_ingest) to produce `iq.duckdb` beside serve.py.

    python examples/make_sample.py
    python serve.py            # open http://127.0.0.1:8090  -> Source: "IQ capture: demo_signal"

Everything here is fake data generated by numpy; it identifies no real device.
"""

import json
import os
import subprocess
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
INGEST = os.path.join(ROOT, "ingest")
SAMPLE_DIR = os.path.join(HERE, "sample_data")

FS = 2_000_000        # 2 Msps
FC = 2_412_000_000    # 2.412 GHz (Wi-Fi ch 1-ish centre, purely cosmetic)
DUR = 0.5             # seconds  -> 1e6 complex samples (~8 MB cf32)


def synth():
    """A complex baseband signal with structure that reads clearly on an STFT."""
    n = int(FS * DUR)
    t = np.arange(n) / FS
    rng = np.random.default_rng(0)
    x = (rng.standard_normal(n) + 1j * rng.standard_normal(n)) * 0.02  # noise floor

    # 1) steady carrier at +400 kHz
    x += 0.5 * np.exp(2j * np.pi * 400_000 * t)

    # 2) frequency-hopping tone: steps across the band every 50 ms
    hops = [-700_000, -300_000, 100_000, 500_000, 800_000, 200_000, -500_000, -100_000, 600_000, 0]
    seg = n // len(hops)
    for i, f in enumerate(hops):
        s = slice(i * seg, (i + 1) * seg)
        x[s] += 0.6 * np.exp(2j * np.pi * f * t[s])

    # 3) periodic wideband bursts (10 ms on / 40 ms off): LTE/Wi-Fi-like TDD
    burst = (np.mod(t, 0.05) < 0.010)
    wb = (rng.standard_normal(n) + 1j * rng.standard_normal(n)) * 0.5
    # keep the burst inside +/-900 kHz so its edges are visible against the band
    x += burst * wb

    return x.astype(np.complex64)


def write_sigmf(x):
    os.makedirs(SAMPLE_DIR, exist_ok=True)
    base = os.path.join(SAMPLE_DIR, "demo_signal")
    x.tofile(base + ".sigmf-data")
    meta = {
        "global": {
            "core:datatype": "cf32_le",
            "core:sample_rate": FS,
            "core:version": "1.0.0",
            "core:description": "Synthetic demo signal (numpy), not real RF.",
        },
        "captures": [{"core:sample_start": 0, "core:frequency": FC}],
        "annotations": [],
    }
    with open(base + ".sigmf-meta", "w") as f:
        json.dump(meta, f, indent=2)
    return base + ".sigmf-meta"


def main():
    print("Generating synthetic SigMF capture ...")
    meta_path = write_sigmf(synth())
    print(f"  wrote {meta_path}")
    print("Running the ingest pipeline (ingest/iq_ingest.py) -> iq.duckdb ...")
    # Resolved exactly as serve.py, atlas.py and verify.py resolve it: IQ_DB
    # first, then ATLAS_DB_DIR, then beside serve.py. Anything else and the demo
    # gets built somewhere the server does not look, which reads as "the demo
    # did not build" rather than "it went elsewhere".
    env = {**os.environ,
           "IQ_DB": os.environ.get("IQ_DB") or os.path.join(
               os.environ.get("ATLAS_DB_DIR") or ROOT, "iq.duckdb")}
    r = subprocess.run([sys.executable, os.path.join(INGEST, "iq_ingest.py"),
                        SAMPLE_DIR, "--dataset", "demo"], env=env, cwd=ROOT)
    if r.returncode != 0:
        sys.exit("iq_ingest failed. See output above.")
    print("\nDone. Now run:  python serve.py")
    print("Then open http://127.0.0.1:8090 and pick Source -> \"IQ capture: demo_signal\".")


if __name__ == "__main__":
    main()
